# Generated by cucumber-sinatra. (2015-05-11 14:18:04 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/app.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SinatraRig

class SinatraRigWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SinatraRigWorld.new
end
